// Copyright (c) The LEGO Group. All rights reserved.
namespace LEGO.AsyncAPI.Models
{
    public static class AsyncApiConstants
    {
        public const string ExtensionFieldNamePrefix = "x-";
        public const string AsyncApi = "asyncapi";
        public const string DollarRef = "$ref";
        public const string Info = "info";
        public const string Servers = "servers";
        public const string Channels = "channels";
        public const string Components = "components";
        public const string Tags = "tags";
        public const string ExternalDocs = "externalDocs";
        public const string Title = "title";
        public const string Description = "description";
        public const string TermsOfService = "termsOfService";
        public const string Contact = "contact";
        public const string License = "license";
        public const string Version = "version";
        public const string Name = "name";
        public const string Url = "url";
        public const string Email = "email";
        public const string Protocol = "protocol";
        public const string ProtocolVersion = "";
        public const string Variables = "";
        public const string Security = "";
        public const string Bindings = "";
        public const string Type = "";
        public const string In = "";
        public const string Scheme = "";
        public const string BearerFormat = "";
        public const string OpenIdConnectUrl = "";
        public const string Flows = "";
        public const string Implicit = "";
        public const string Password = "";
        public const string ClientCredentials = "";
        public const string AuthorizationCode = "";
        public const string Basic = "";
        public const string Flow = "";
        public const string AuthorizationUrl = "";
        public const string TokenUrl = "";
        public const string Scopes = "";
        public const string Application = "";
        public const string AccessCode = "";
        public const string Enum = "";
        public const string Default = "";
        public const string Examples = "";
        public const string Id = "";
        public const string DefaultContentType = "";
        public const string OperationId = "";
        public const string Summary = "";
        internal static string Traits;
        internal static string Message;
        internal static string MultipleOf;
        internal static string Maximum;
        internal static string ExclusiveMaximum;
        internal static string Minimum;
        internal static string ExclusiveMinimum;
        internal static string MaxLength;
        internal static string MinLength;
        internal static string Pattern;
        internal static string MaxItems;
        internal static string MinItems;
        internal static string UniqueItems;
        internal static string MaxProperties;
        internal static string MinProperties;
        internal static string Required;
        internal static string Const;
        internal static string AllOf;
        internal static string AnyOf;
        internal static string OneOf;
        internal static string Not;
        internal static string Contains;
        internal static string If;
        internal static string Then;
        internal static string Else;
        internal static string Items;
        internal static string Properties;
        internal static string AdditionalProperties;
        internal static string Format;
        internal static string Nullable;
        internal static string Discriminator;
        internal static string ReadOnly;
        internal static string WriteOnly;
        internal static string Deprecated;
        internal static string Schema;
        internal static string Location;
        internal static string Subscribe;
        internal static string Publish;
        internal static string Parameters;
    }
}